const products = [
  {
    id: 1,
    title: 'Apple watch',
    description: 'Series 5 SE',
    rating: '⭐⭐⭐⭐',
    price: 529.99,
    currency: '$',
    imageUrl: 'http://surl.li/kebsi',
    specs: [
     'Apple Watch Series 5 and Apple Watch Series 3 have a water resistance rating of 50 meters under ISO standard 22810:2010. This means that they may be used for shallow-water activities like swimming in a pool or ocean. However, they should not be used for scuba diving, waterskiing, or other activities involving high-velocity water or submersion below shallow depth. Apple Watch Series 5 (GPS + Cellular) can use a cellular connection for Emergency SOS. To use Emergency SOS on an Apple Watch without cellular, your iPhone needs to be nearby. If your iPhone isn’t nearby, your Apple Watch needs to be connected to a known Wi-Fi network and you must set up Wi-Fi Calling.'
    ],
  },
  {
    id: 2,
    title: 'Sony ZX3',
    description: 'Light Grey',
    rating: '⭐⭐⭐',
    price: 39.99,
    currency: '$',
    imageUrl: 'http://surl.li/kebry',
    specs: [
      'The slim, swivel and folding style earcups stow away for compact portability. Wireless Connectivity: The headphones feature wireless Bluetooth technology, providing seamless connectivity to your devices. This ensures freedom of movement without the hassle of tangled wires. Exceptional Sound: With advanced audio technology, the Sony ZX3 headphones deliver high-quality sound with deep bass, clear mids, and crisp highs. This results in a well-balanced audio profile suitable for a wide range of music genres and multimedia content. The lightweight, adjustable headband with swivel ear pads is designed for comfort so you can enjoy extended listening sessions without fatigue.',
    ],
  },
  {
    id: 3,
    title: 'iPhone 11',
    description: 'Serious Black',
    rating: '⭐⭐⭐⭐⭐',
    price: 619.99,
    currency: '$',
    imageUrl: 'http://surl.li/kebro',
    specs: [
      'Display: Liquid Retina HD display',
      'Processor: A13 Bionic chip',
      'Camera System: Dual 12MP Ultra Wide and Wide cameras',
      'Face ID: Enabled for secure authentication',
      'Battery Life: Up to 17 hours of talk time',
      'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
    ],
  },
  {
    id: 4,
    title: 'iPhone 11',
    description: 'Subway Blue',
    rating: '⭐⭐⭐⭐⭐',
    price: 619.99,
    currency: '$',
    imageUrl: 'http://surl.li/kebrk',
    specs: [
      'Display: Liquid Retina HD display',
      'Processor: A13 Bionic chip',
      'Camera System: Dual 12MP Ultra Wide and Wide cameras',
      'Face ID: Enabled for secure authentication',
      'Battery Life: Up to 17 hours of talk time',
      'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
    ],
  },
  {
    id: 5,
    title: 'iPhone 11',
    description: 'Product Red',
    rating: '⭐⭐⭐⭐⭐',
    price: 619.99,
    currency: '$',
    imageUrl: 'http://surl.li/kebrd',
    specs: [
      'Display: Liquid Retina HD display',
      'Processor: A13 Bionic chip',
      'Camera System: Dual 12MP Ultra Wide and Wide cameras',
      'Face ID: Enabled for secure authentication',
      'Battery Life: Up to 17 hours of talk time',
      'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
    ],
  },
  {
    id: 6,
    title: 'iPhone 11',
    description: 'Milky White',
    rating: '⭐⭐⭐⭐⭐',
    price: 619.99,
    currency: '$',
    imageUrl: 'http://surl.li/kebqe',
    specs: [
      'Display: Liquid Retina HD display',
      'Processor: A13 Bionic chip',
      'Camera System: Dual 12MP Ultra Wide and Wide cameras',
      'Face ID: Enabled for secure authentication',
      'Battery Life: Up to 17 hours of talk time',
      'Water Resistance: Rated IP68 (maximum depth of 2 meters up to 30 minutes)',
    ],
  },
  {
    id: 7,
    title: 'iPhone 13',
    description: 'Product Red',
    rating: '⭐⭐⭐⭐⭐',
    price: 699.00,
    currency: '$',
    imageUrl: 'http://surl.li/kebqm',
    specs: [
      'Display: Super Retina XDR display',
      'Processor: A15 Bionic chip',
      'Camera System: Dual 12MP Ultra Wide and Wide cameras with Night mode',
      'Face ID: Enabled for secure authentication',
      'Battery Life: Up to 22 hours of talk time',
      'Water Resistance: Rated IP68 (maximum depth of 6 meters up to 30 minutes)',
    ],
  },
  {
    id: 8,
    title: 'iPhone 14',
    description: 'Product Red',
    rating: '⭐⭐⭐⭐⭐',
    price: 619.99,
    currency: '$',
    imageUrl: 'http://surl.li/kebqw',
    specs: [
      'Display: Super Retina XDR display',
      'Processor: A16 Bionic chip',
      'Camera System: Triple 12MP Ultra Wide, Wide, and Telephoto cameras',
      'Face ID: Enabled for secure authentication',
      'Battery Life: Up to 24 hours of talk time',
      'Water Resistance: Rated IP68 (maximum depth of 6 meters up to 30 minutes)',
    ],
  },
];

export default products;


